// Edit or add prompts here. Each category is a list of strings.
const PROMPTS = {
  People: [
    "What is something about a person you no longer speak to that you remember more clearly than you expected to?",
    "Who is someone you haven't spoken to in years, yet you could still recognize their voice immediately?",
    "What small habit of someone from your past can you still remember without trying?",
    "Who once knew a version of you that no longer exists?",
    "What is something someone used to say that you didn't appreciate until much later?",
    "Who is someone you remember mostly through ordinary moments rather than important ones?",
    "What person comes to mind when you think about a particular season of your life?",
    "Who could you once call without thinking twice, but would now hesitate to contact?",
    "What is a conversation with someone that ended normally, even though you didn't know it would be your last?",
    "Who is someone you wish you had asked more questions while you still had the chance?",
    "What is something you learned about a person only after you were no longer close to them?",
    "Who is someone whose handwriting you think you would recognize immediately?",
    "What person is attached to a place you haven't visited in a long time?",
    "Who made an ordinary part of your life feel special without ever realizing it?",
    "What is the first thing you remember about someone who eventually became important to you?",
    "Who is someone you remember differently now than you did when you knew them?",
    "What person's name carries an entire period of your life with it?",
    "Who is someone you once saw almost every day but now know almost nothing about?",
    "What is something you remember about someone that they probably don't remember themselves?",
    "Who is someone you would recognize from a distance, even after many years?",
    "What person appears unexpectedly in your mind when you hear a particular song?",
    "Who is someone you never properly said goodbye to?",
    "What is one ordinary thing that still reminds you of someone?",
    "Who is someone you used to know through a shared routine?",
    "What is a kindness someone gave you that they probably considered insignificant?",
    "Who made you laugh during a time when you don't remember having much to laugh about?",
    "What is something you wish you had noticed more about someone while they were still part of your everyday life?",
    "Who is someone you remember by the way they walked into a room?",
    "What person's absence did you notice only after some time had passed?",
    "Who is someone you wonder about occasionally but will probably never ask about?",
    "What is a question about someone from your past that you still don't have an answer to?",
    "Who once knew exactly how to make you feel better?",
    "What is something you inherited from someone without realizing it?",
    "Who taught you something that has stayed with you long after you forgot the lesson itself?",
    "What person do you associate with a particular smell?",
    "Who is someone whose face you remember more clearly than their voice?",
    "What is one photograph that makes you think about the people who were there but aren't in your life anymore?",
    "Who is someone you remember because of the way they said your name?",
    "What person from your childhood would you most like to hear from again, even just for a few minutes?",
    "Who once occupied a large part of your life but now exists mostly in memories?",
    "What is something you never told someone because you assumed there would always be another opportunity?",
    "Who is someone you used to understand easily but eventually grew distant from?",
    "What person do you associate with a particular time of day?",
    "Who is someone whose life you sometimes wonder about when you see people of the same age?",
    "What is something you wish you could tell a person from your past about the life you have now?",
    "Who is someone you remember through the objects they used to carry?",
    "What person is connected to a particular road, bus route, classroom, or building in your memory?",
    "Who was the first person who made you feel understood without needing to explain much?",
    "What is something about someone that you didn't realize you were memorizing?",
    "Who is someone you once thought would remain in your life forever?",
    "What person do you associate with the feeling of coming home?",
    "Who is someone whose life probably changed in ways you know nothing about?",
    "What is the oldest memory you have of someone who is still somewhere in the world?",
    "Who is someone you remember mostly because of the things you did together?",
    "What person would you place beside your younger self if you could revisit one ordinary day?",
    "Who is someone you wish you could watch living an ordinary day again?",
    "What is something you remember someone doing that made you realize, only years later, how much they cared?",
    "Who is someone you once took for granted simply because they were always there?",
    "What person do you associate with a particular kind of weather?",
    "Who is someone you have outgrown but still feel grateful for?",
    "What is one thing about a person that time has failed to make you forget?",
    "Who is someone you remember whenever you return to a place you once shared?",
    "What person from your past would be surprised by the person you became?",
    "Who is someone you would like to sit beside again without needing to talk?",
    "What is something you wish you had understood about a person when you were younger?",
    "Who is someone whose absence changed the shape of your everyday life?",
    "What person do you remember through a single afternoon, evening, or morning?",
    "Who is someone you wonder whether you ever cross their mind too?",
    "What is a memory involving another person that becomes more meaningful the older you get?",
    "Who is someone you once knew so well that you could predict what they would say, and can no longer predict at all?",
    "What person would you thank if you could return to one particular moment in your life?",
    "Who is someone you haven't thought about in years, but you suspect you would remember everything once you saw them again?",
    "If you could return to one completely ordinary day with someone from your past—not to change anything, only to experience it again—which day would you choose?"
  ],
  Places: [
    "What place from your childhood can you still picture without closing your eyes?",
    "What ordinary place became important to you only after you stopped going there?",
    "Is there somewhere you once wanted desperately to leave, but now wish you could visit once more?",
    "What place feels different in your memory than it probably looked in reality?",
    "Which room from your past could you still walk through in your mind?",
    "What street carries a memory you haven't thought about in years?",
    "Is there a place you associate so strongly with one person that it feels strange to imagine anyone else there?",
    "What place did you never realize you were seeing for the last time?",
    "Which building from your younger years has probably changed the most?",
    "What place do you remember mostly because of what you felt there?",
    "Is there somewhere you pass occasionally that still makes you remember who you used to be?",
    "What was your favorite place to sit when you were younger?",
    "Which place felt enormous when you were a child but would probably seem small now?",
    "What place once felt like home without actually being your home?",
    "Is there a place you associate with a particular sound?",
    "What place do you remember visiting on a day that seemed ordinary at the time?",
    "Which place would you return to if you could experience one afternoon there exactly as it happened?",
    "What place did you spend countless hours in without realizing those hours would become memories?",
    "Is there a corner of a building you remember more vividly than the building itself?",
    "What place makes you remember a particular version of yourself?",
    "Which place do you remember through its smell?",
    "What place looked especially beautiful because of the people you were with?",
    "Is there somewhere you have never returned to because you are afraid it wouldn't feel the same?",
    "What place from your past exists now only in photographs and memory?",
    "Which classroom, office, shop, or waiting area holds an unexpectedly important memory for you?",
    "What place did you once consider boring that you now wish you could see again?",
    "Is there a road you associate with going somewhere you were excited to be?",
    "What place reminds you of a time when your life felt completely different?",
    "Which place do you remember most clearly at a particular time of day?",
    "What place would your younger self be surprised to know you still remember?",
    "Is there a place you visited only once but somehow never forgot?",
    "What place do you remember because of the weather that day?",
    "Which place felt safest to you during a particular period of your life?",
    "What place became meaningful because of something that happened there only once?",
    "Is there somewhere you used to visit regularly that disappeared quietly from your life?",
    "What place do you associate with waiting?",
    "Which place do you remember from looking out of a window?",
    "What place would you photograph differently if you knew then that you would miss it later?",
    "Is there a place whose name alone brings back an entire chapter of your life?",
    "What place did you share with people who are no longer part of your everyday life?",
    "Which place do you remember as being full of people, even though you can now picture it completely empty?",
    "What place makes you remember being younger than you realized you were?",
    "Is there somewhere you wish you had paid more attention to before leaving?",
    "What place from your past would you want to stand in again without changing anything?",
    "Which place do you associate with a particular song?",
    "What place once seemed permanent but is no longer there?",
    "Is there a place you remember visiting when you didn't yet know how much your life was about to change?",
    "What place do you associate with the feeling of being on your way somewhere?",
    "Which place made you feel like you belonged, even temporarily?",
    "What place do you remember from a single evening?",
    "Is there somewhere you used to go when you needed to be alone?",
    "What place would you recognize immediately even if everything around it had changed?",
    "Which place holds a memory you rarely tell anyone about?",
    "What place do you associate with the beginning of something?",
    "What place do you associate with the end of something?",
    "Is there a place you once dreamed of returning to but eventually stopped mentioning?",
    "What place from your past would you like to see through your younger eyes again?",
    "Which place do you remember differently depending on what age you were?",
    "What place seemed ordinary to everyone else but felt significant to you?",
    "Is there a place you have forgotten the address of but could still describe perfectly?",
    "What place do you remember through the people who used to gather there?",
    "Which place would you revisit just to hear its familiar sounds one more time?",
    "What place feels strangely close even though it is far away now?",
    "Is there somewhere you once thought you would return to many times, but never did?",
    "What place would you want to visit at the exact same hour and on the exact same kind of day as your memory?",
    "Which place carries a memory you didn't understand the importance of until years later?",
    "What place makes you wonder what has happened there since you left?",
    "Is there a place you sometimes imagine walking through again when you're thinking about the past?",
    "What place would you show someone if you wanted them to understand who you used to be?",
    "Which place from your past feels almost like a dream now?",
    "What place would you return to if you were allowed only one hour and nothing was allowed to change?",
    "Is there somewhere you still think of as “ours,” even though the people who made it feel that way are gone from your life?",
    "What place from your childhood would you want to see at the exact same time of day?",
    "Which familiar place do you wonder about when you realize how much it has probably changed?",
    "What place did you once pass every day without ever stopping to appreciate it?",
    "Is there somewhere you remember more vividly at night than during the day?",
    "What place do you associate with the first time you felt independent?",
    "Which place would you visit if you could borrow your younger self's eyes for an hour?",
    "What place do you remember through the view from a particular seat?",
    "Is there a place you left without realizing part of your life was staying behind?",
    "What place became meaningful simply because you kept returning to it?",
    "Which place would you like to find exactly as you remember it?",
    "What place do you associate with the feeling of not wanting the day to end?"
  ],
  Time: [
    "What year of your life feels much closer than it actually is?",
    "Which season of your life do you sometimes wish you could step back into for one afternoon?",
    "What age were you when you first realized that time could change everything?",
    "What ordinary day from your past would you choose to live again?",
    "Which year disappeared faster than you expected?",
    "What period of your life feels like it belonged to someone else?",
    "What did you believe would last forever when you were younger?",
    "Which season do you associate most strongly with a particular memory?",
    "What was the last ordinary day before something in your life changed?",
    "What part of your childhood now feels impossibly far away?",
    "Which month carries the most memories for you?",
    "What year would you revisit if you could observe it without changing anything?",
    "When did you last feel completely unaware that time was passing?",
    "What age do you remember most vividly?",
    "Which period of your life seemed endless while you were living through it?",
    "What once felt like a distant future that has already become your past?",
    "What was something you used to think you had plenty of time for?",
    "Which birthday do you remember most clearly?",
    "What season used to mean something different to you?",
    "When was the last time you remember being genuinely excited about something simple?",
    "What period of your life would you describe using only three memories?",
    "Which year would you like to watch from beginning to end?",
    "What did you once do every day that you suddenly stopped doing?",
    "When did you first notice yourself growing older?",
    "What childhood expectation about adulthood turned out differently than you imagined?",
    "Which year contains a version of you that you sometimes miss?",
    "What was the longest summer, holiday, or break you can remember?",
    "When did an ordinary routine quietly become a memory?",
    "What moment from your past seems to have lasted much longer in your memory than it actually did?",
    "Which age would you revisit, not because it was perfect, but because it was yours?",
    "What did you once rush through that you wish you had experienced more slowly?",
    "When was the last time you didn't know you were living through something you would later miss?",
    "Which season of your life ended without you noticing?",
    "What year do you remember mostly through photographs?",
    "What is something you used to think was “recent” that happened years ago?",
    "When did a familiar part of your life begin to feel different?",
    "Which period of your life would you like to explain to your present self?",
    "What did you once believe you would have figured out by now?",
    "Which age feels most unlike who you are today?",
    "What was the first goodbye that made you understand that some things really don't return?",
    "When did you last experience a day that seemed to contain no future at all?",
    "What year would you give to someone who wanted to understand your younger self?",
    "Which memory becomes softer every time you return to it?",
    "What did you once count down the days toward?",
    "When did waiting feel longer than the event itself?",
    "Which chapter of your life ended quietly?",
    "What period would you like to experience again without knowing what comes next?",
    "When was the last time you felt that a particular day would never end?",
    "What age would you tell your younger self not to rush through?",
    "Which year changed you in ways you didn't recognize at the time?",
    "What did you think you would remember forever but have almost completely forgotten?",
    "When did you last look forward to something that no longer exists?",
    "Which season makes you feel that time is moving too quickly?",
    "What part of your life passed while you were busy looking toward what came next?",
    "When did you last realize that something had already become a memory?",
    "What year would you revisit just to see what you were worried about then?",
    "Which childhood memory has survived despite everything else you have forgotten?",
    "What did you once consider old that now seems surprisingly recent?",
    "When did a year begin to feel shorter than the one before it?",
    "Which moment from your past would you freeze if you could?",
    "What is something you remember waiting for that eventually arrived and disappeared almost immediately?",
    "Which chapter of your life feels unfinished even though it ended years ago?",
    "When did you last feel completely present without thinking about what came next?",
    "What age would you like to meet again, just to see what you were like?",
    "Which year would you erase from your memory only to experience discovering it again?",
    "What was the last period of your life when your future felt completely unknown?",
    "When did something you once considered temporary become part of your identity?",
    "What season of your life would you describe as a photograph rather than a story?",
    "Which year do you associate with the most change?",
    "What did you leave behind without realizing you were leaving it behind?",
    "When did you first understand that adults had been younger once too?",
    "What moment from childhood seems impossibly small but remains in your memory?",
    "Which period of your life would you like to watch from a distance?",
    "What did you once think you would never miss?",
    "When did you last feel surprised by how quickly a year had passed?",
    "Which memory makes you realize how much time has actually gone by?",
    "What part of your life feels like it happened only yesterday?",
    "If you could spend one ordinary day in any year of your life, which year would you choose?",
    "If time could give you one day back—not to change it, only to live it again—which day would you ask for?",
    "What moment would you stay in a little longer if you had known how quickly it would become a memory?",
    "Which year would you like to hear your younger self describe in their own words?",
    "What part of your past do you think you will miss more as you get older?",
    "When did you last realize that you were standing inside a moment you would one day remember?"
  ],
  Things: [
    "What object from your past could tell the most accurate story about you?",
    "What is something you owned as a child that you wish you had kept?",
    "Which object in your room has been with you longer than most people realize?",
    "What ordinary item reminds you immediately of someone?",
    "What is something you used every day without realizing you would eventually stop?",
    "Which old photograph would you save if you could keep only one?",
    "What object do you associate with a particular period of your life?",
    "What is something you once considered worthless that you now wish you had kept?",
    "Which piece of clothing carries a memory you haven't forgotten?",
    "What object reminds you of a home you no longer live in?",
    "Is there something you still own simply because throwing it away feels impossible?",
    "What is the oldest thing you still have?",
    "Which object would your younger self immediately recognize?",
    "What ordinary object makes you remember a particular person?",
    "What is something you lost that you still remember looking for?",
    "Which photograph do you wish you could step inside?",
    "What object has survived several versions of you?",
    "Is there something you kept even though you haven't used it in years?",
    "What smell is attached to an object you remember from childhood?",
    "Which book reminds you of who you were when you first read it?",
    "What piece of paper from your past would you like to read again?",
    "What object did you once carry everywhere?",
    "Which old possession would surprise people if they knew why you kept it?",
    "What is something you wish you had photographed before it disappeared?",
    "Which object reminds you of a particular journey?",
    "What item in your home has a story you rarely tell?",
    "Is there something you own that belonged to someone before you?",
    "What object would you return to your younger self if you could?",
    "Which old photograph contains more meaning now than it did when it was taken?",
    "What is something you used to collect?",
    "Which object makes you remember a particular sound?",
    "What is the first object you remember believing was truly yours?",
    "Which possession did you once love but eventually outgrow?",
    "What object would you rescue from a box of forgotten things?",
    "Is there something you kept because of who gave it to you rather than what it is?",
    "What object from your childhood would you like to hold again?",
    "Which everyday item has changed more than you realized over the years?",
    "What is something you used to write with, listen to, carry, or wear that has almost disappeared from your life?",
    "Which object reminds you of school?",
    "What old item makes you remember a particular room?",
    "Is there something you threw away that you still think about occasionally?",
    "What object would you show someone if you wanted them to understand your childhood?",
    "Which possession feels strangely connected to a person you no longer see?",
    "What object did you once think you would keep forever?",
    "Which photograph makes you remember what happened immediately before or after it was taken?",
    "What is something you once saved carefully but can no longer remember why?",
    "Which object has been present through several important changes in your life?",
    "What old message, note, or letter would you like to read one more time?",
    "Is there an object you recognize by touch even in the dark?",
    "What item reminds you of a particular holiday?",
    "Which object would you place in a time capsule representing your life right now?",
    "What is something small that carries an unexpectedly large memory?",
    "Which old possession makes you wonder who you were when you first got it?",
    "What object would you want to find in a drawer twenty years from now?",
    "Is there something you keep because it proves that a particular moment really happened?",
    "What object has changed meaning as you have grown older?",
    "Which photograph makes you wish you could hear what everyone was saying?",
    "What is something you once borrowed and never forgot?",
    "Which object reminds you of a person even though they never gave it to you?",
    "What thing from your childhood would probably seem strange to a child today?",
    "What is the most ordinary object you have ever attached a memory to?",
    "Which object would you recognize immediately from its sound alone?",
    "Is there something you keep even though you know you will probably never use it again?",
    "What old possession would you ask your younger self about if it could answer?",
    "Which object reminds you of the person you were before something changed?",
    "What is something you once thought was permanent but eventually disappeared?",
    "Which photograph would you take differently if you could stand there again?",
    "What object makes you remember a time when your family was different?",
    "Is there something you wish you had kept simply because it belonged to an earlier version of your life?",
    "What object from your past would you put on a table and let it tell its own story?",
    "Which thing do you own that has witnessed more of your life than most people have?",
    "What old object makes you wonder where the years went?",
    "Which possession would be hardest to explain to someone who didn't know your history?",
    "What is something you once used so often that you stopped noticing it?",
    "Which object do you hope never becomes meaningless to you?",
    "What photograph would you want to look at again when you are much older?",
    "What is one thing you wish you could hold again for a few seconds?",
    "Which object carries the memory of a person without carrying anything they said?",
    "What ordinary thing from your past would you recognize anywhere?",
    "Which possession would you save if you had to leave your home with only one small bag?",
    "What object from your life would your future self be grateful you kept?",
    "If every object you owned suddenly became a memory instead of a possession, which one would you be most afraid to lose?",
    "What is something you own today that you hope will still be with you years from now?"
  ],
  Unspoken: [
    "What is something you wish you had said before the moment passed?",
    "What conversation do you sometimes replay differently in your mind?",
    "Who is someone you owe words to but may never speak them?",
    "What did you leave unsaid because you thought there would be another chance?",
    "What is something you understood only after it was too late to say so?",
    "Which apology have you never given?",
    "What thank-you have you never properly expressed?",
    "What truth did you know but choose not to say?",
    "Is there something you wish someone had asked you when you were younger?",
    "What would you tell someone if you knew you would never see them again?",
    "What question have you carried for years without asking?",
    "What did you pretend not to care about because admitting that you cared felt too difficult?",
    "Is there a goodbye you wish had been different?",
    "What feeling did you never find the right words for?",
    "What is something you wish you had asked your parents, grandparents, or older relatives while you could?",
    "What did you want someone to understand without having to explain it?",
    "Which conversation ended before you were ready for it to end?",
    "What would you say to a younger version of yourself if they could hear you?",
    "What is something you wish someone from your past knew about how you remember them?",
    "What did you keep quiet because saying it might have changed everything?",
    "Is there a question you are afraid would have an answer?",
    "What is something you once wanted to confess but never did?",
    "Who do you wish you could thank for something they probably never realized they did?",
    "What words from someone else have stayed with you even though you never told them?",
    "What did you wish someone had noticed without you asking?",
    "What is something you would say if embarrassment no longer existed?",
    "Which sentence from your past would you change if you could?",
    "What do you wish you had said during your last ordinary conversation with someone?",
    "Is there someone you would speak to differently if you knew how little time you had left together?",
    "What did you misunderstand because neither of you said what you really meant?",
    "What is something you have forgiven without ever saying that you forgave it?",
    "What is something you still wish someone would apologize for?",
    "What would you tell someone who remembers you differently from how you remember yourself?",
    "Which words have you been waiting years to hear?",
    "What is something you wish you had asked before someone became a stranger?",
    "What did you once hope someone would notice about you?",
    "Is there something you still cannot bring yourself to say aloud?",
    "What would you tell the person you were five years ago about what happened afterward?",
    "What is one truth about your life that you rarely say even to yourself?",
    "Which conversation do you wish you could have one more time, knowing exactly what you know now?",
    "What would you say to someone who changed your life without ever knowing they did?",
    "What is something you have carried quietly for so long that you sometimes forget it was never spoken?",
    "If you were given one final conversation with anyone from your past, and you knew there would be no second chance to say what remained unsaid, what would you finally say?"
  ]
};
