// Edit or add prompts here. Each category is a list of strings.
const PROMPTS = {
  Journal: [
    "Describe today in three sentences, then add one detail you would otherwise forget.",
    "What is taking up the most space in your mind right now?",
    "Write about a small moment from this week that made you smile.",
    "What did you avoid today, and why?",
    "List five things you noticed today that you usually overlook.",
    "Write a letter to yourself one year from now.",
    "What is one thing you are looking forward to?",
    "Describe the room you are sitting in as if you were seeing it for the first time.",
    "What conversation from today are you still thinking about?",
    "What would make tomorrow feel like a good day?",
    "Write about a habit you are trying to build or let go of.",
    "What is something you are grateful for that you rarely say out loud?",
    "How did your body feel today? Where did you carry tension?",
    "Write about a decision you are putting off.",
    "What did you learn recently that surprised you?",
    "Describe your morning routine and what you would change about it.",
    "What is a worry you could set down for tonight?",
    "Write about someone who made your day easier.",
    "What did you do today that felt like you?",
    "Finish this sentence five different ways: \"Lately, I have been...\""
  ],
  Writing: [
    "Write a scene that takes place entirely in a waiting room.",
    "Begin a story with the line: \"The letter arrived three years too late.\"",
    "Describe a character through the contents of their coat pockets.",
    "Write a conversation in which neither person says what they really mean.",
    "A lighthouse keeper receives an unexpected visitor. What happens next?",
    "Write about a place using only sound.",
    "Tell a story that begins at the end of a long journey.",
    "Write a paragraph in which the weather reflects a character's mood without naming it.",
    "Describe a childhood kitchen so vividly that a stranger could draw it.",
    "Write a short scene where someone finds an object that does not belong to them.",
    "Invent a small town with one strange local custom.",
    "Write a poem about something you touch every day.",
    "Write a monologue for someone who is packing up a house.",
    "Two old friends meet by chance at a train station. Write their first minute.",
    "Rewrite a memory from the point of view of someone else who was there.",
    "Write a story in exactly one hundred words.",
    "Describe a stranger you saw recently and invent their evening.",
    "Write about a door that has always been kept locked.",
    "Begin a story with someone deciding not to leave.",
    "Write a scene set in a library after closing time."
  ],
  Photography: [
    "Photograph something small that catches the light.",
    "Find three different shades of one colour on your walk today.",
    "Take a picture of a shadow instead of the object that casts it.",
    "Photograph a place you pass every day as if you were a visitor.",
    "Capture a reflection: a window, a puddle, a spoon.",
    "Make a photograph that shows how quiet it is.",
    "Photograph your hands doing something ordinary.",
    "Find a pattern hiding in the everyday and frame it closely.",
    "Take a picture from the lowest angle you can manage.",
    "Photograph an empty chair and let it tell a story.",
    "Capture the light at the same spot in the morning and again in the evening.",
    "Look for texture: peeling paint, worn stone, woven cloth.",
    "Photograph something through a doorway or window frame.",
    "Take a photograph that includes only the edges of things.",
    "Find beauty in something old or worn.",
    "Photograph the view from where you are sitting right now.",
    "Capture a moment of movement, or its blur.",
    "Photograph an object that reminds you of someone.",
    "Take a portrait of a place without any people in it.",
    "Make a picture that feels like the hour before dusk."
  ],
  Reading: [
    "Which book has stayed with you the longest, and why?",
    "Write down a sentence you read recently that you wish you had written.",
    "Which character would you most like to have dinner with?",
    "Describe a book that arrived in your life at exactly the right time.",
    "What genre do you rarely read, and what might it offer you?",
    "Reread the first page of a favourite book. What do you notice now?",
    "What book do you keep meaning to read, and what keeps stopping you?",
    "Choose a passage you love and write about why it works.",
    "Which book changed your mind about something?",
    "Write a short letter to an author whose work you admire.",
    "Where do you read best? Describe the setting in detail.",
    "What is the most memorable opening line you know?",
    "Pick a book from your shelf at random. What does the cover promise?",
    "Which fictional place would you most like to visit?",
    "Write about a book you abandoned and what it taught you.",
    "What have you read that you keep recommending to others?",
    "Copy out one paragraph by hand and notice its rhythm.",
    "Which book reminds you of a certain season?",
    "Imagine the book you wish existed. What is it about?",
    "What are you reading now, and what is it asking of you?"
  ],
  Reflection: [
    "What are you holding on to that you could gently let go of?",
    "When did you last feel truly at ease?",
    "What does a good life look like for you right now?",
    "Which of your values have you honoured this week?",
    "What would you tell your younger self about today's worries?",
    "What do you need more of in your days? What do you need less of?",
    "Where in your life are you being too hard on yourself?",
    "What has changed in you over the past year?",
    "Who do you become when you feel safe?",
    "What are you learning to accept?",
    "What is enough for you right now?",
    "When do you feel most like yourself?",
    "What are you curious about lately?",
    "What small act of kindness could you offer yourself today?",
    "Which fear has shrunk since you first faced it?",
    "What does rest mean to you, and are you allowing it?",
    "What are you proud of that no one has noticed?",
    "What is one boundary that would make your life gentler?",
    "What question are you living with at the moment?",
    "If you slowed down by ten percent, what would you notice?"
  ]
};
